# .github/workflows/renovate.yaml
name: Renovate

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Use a recent LTS Node.js version

      - name: Install Renovate
        run: npm install -g renovate

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Run Renovate
        run: renovate --autodiscover
        env:
          # Pass the GitHub token to Renovate via RENOVATE_TOKEN environment variable
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}
          # Specify the platform (GitHub)
          RENOVATE_PLATFORM: github
          # Specify the repository to process
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
