# .github/workflows/renovate.yaml
name: Renovate

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.2
        with:
          # Pass the GitHub token to Renovate
          token: ${{ secrets.GITHUB_TOKEN }}